config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'pages#homepage' 

  resources :conversions 

  resources :items

  resources :inventories

  resources :purchases

  get 'signup', to: 'users#new'
  resources :users, expect: [:new] 
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/inventory.rb
class Inventory < ApplicationRecord
    
    has_many :merge_tables
    #has_one :merge_table
    has_many :items, :through => :merge_tables, :dependent => :destroy
    accepts_nested_attributes_for :items, allow_destroy: true

    validates :name, presence: true, uniqueness: true
    validates :selling_units, presence: true
    validates :user_id, presence: true
    validates :items, presence: true
    #validates :user_id, presence: true
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  def index
    @inventories = Inventory.all
    @item = Item.new
  end

  def new
    @inventory = Inventory.new
    @inventory.items.build
  end

  def create
    #render plain: params[:inventory].inspect
    @inventory = Inventory.new(inventory_params)
    @inventory.user_id = current_user.id
    item_list = params[:inventory][:items_attributes].values
    item_list.each do |item|
      unless item.empty?
        if item[:_destroy] == "false"
          @item = Item.find(item[:id])
          @inventory.items << @item
        end
      end
    end

    #Remove Duplicate Items If any
    @inventory.items = @inventory.items.uniq()
    @inventory.user_id = current_user.id
    if @inventory.save
      #debugger
      #Adding the Quantity to MergeTable Model
      quant = Hash.new
      @inventory.items.each do |item|
        val = MergeTable.where(inventory: @inventory, item: item).first
        selval = item_list.detect { |i| i["id"].to_i == item.id }
        quant.store(val.id, { "quantity" => selval["merge_table_ids"].to_i })
      end
      if MergeTable.update(quant.keys, quant.values)
        flash[:success] = "Product Saved"
        redirect_to inventories_path
      else
        flash[:error] = "Product Save Unsuccessfull"
        render :new
      end
    else
      flash[:error] = "Product Save Unsuccessfull"
      render :new
    end
  end

  def destroy
    @inventory = Inventory.find(params[:id])
    @inventory.items.clear
    if @inventory.delete
      flash[:success] = "Item deleted!"
      redirect_to inventories_path
    else
      flash[:error] = "Failed to delete this Item!"
      render :index
    end
  end

  def edit
    @inventory = Inventory.find(params[:id])
    #@mergeList = @inventory.merge_tables
  end

  def update
    @inventory = Inventory.find(params[:id])
    #@mergeList = @inventory.merge_tables
    @inventory.items.clear
    item_list = params[:inventory][:items_attributes].values
    item_list.each do |item|
      unless item.empty?
        if item[:_destroy] == "false"
          @item = Item.find(item[:id])
          @inventory.items << @item
        end
      end
    end
    @inventory.items = @inventory.items.uniq()

    #Adding the Quantity to MergeTable Model
    quant = Hash.new
    @inventory.items.each do |item|
      val = MergeTable.where(inventory: @inventory, item: item).first
      selval = item_list.detect { |i| i["id"].to_i == item.id }
      quant.store(val.id, { "quantity" => selval["merge_table_ids"].to_i })
    end
    @inventory.user_id = current_user.id
    if @inventory.update(inventory_params) and MergeTable.update(quant.keys, quant.values)
      flash[:success] = "Item updated!"
      redirect_to inventories_path
    else
      flash[:error] = "Failed to edit Item!"
      render :edit
    end
  end

  private

  def inventory_params
    params.require(:inventory).permit(:name, :selling_units)
  end
end

app/views/inventories/_item.html.erb
<div>
    <span class="raw_internal">
        <%= b.select :id, Item.all.collect { |p| [ p.title, p.id,{'unit' => Conversion.find_by(name: Item.find(p.id).try(:title)).try(:conversion_units), 'inp_id' => b.options[:child_index]} ] },
        { include_blank: false }, { :class => 'prod_input prod_select', :onchange => 'handleChange(event)', id: 'id_select_'+b.options[:child_index].to_s, 'title'=>'Raw Material' }  %> 
        <%= b.hidden_field :_destroy %>
        <% itm_id = b.object.id%>
        <% itm =  Item.where(id: itm_id).first%>
        <%#a = Item.where(id: itm_id).first.merge_tables.where(inventory: @inventory, item_id: itm_id).first.quantity%>
        <%#=b.text_field :merge_table_ids, label: false, value: itm_q, class:"prod_input prod_inp_quant"%>
        <%#= debug @inventory.items.where(id: a).first %>
        <%#= debug @inventory.items.where(id: 1).first.id%>
        <%#= debug b.object.join_item %>
        <%= b.text_field :merge_table_ids, label: false, value: itm_q, class:"prod_input prod_inp_quant tooltip", 'title'=>'Quantity'%>
        <% unit = Conversion.find_by(name: itm.try(:title)).conversion_units if Conversion.find_by(name: itm.try(:title))%>
        <%# b.label unit%>
        <%= text_field_tag :virtual_unit, unit , class:"prod_input prod_inp_quant", disabled: true, id: 'id_unit_'+b.options[:child_index].to_s, 'title'=>'Raw material Units' %>
        <%#= b.select :purchase_units, ['KGS', 'BOX', 'PKT', 'NOS', 'BOT'],{ include_blank: false }, { :class => 'modal_select_unit' }%>
        <%= link_to '<i class="fas fa-trash-alt icon_delete"></i>'.html_safe, '#', class: 'remove_raw'%>
    </span>
</div>

<script>
    function handleChange(event) {
        src_id = event.srcElement.id;
        value = $('#'+src_id).find(':selected').attr('unit');
        inp_id = $('#'+src_id).find(':selected').attr('inp_id');
        $('#id_unit_'+inp_id).val(value);
    }
</script>

app/views/inventories/edit.html.erb
<div class="form_container">
  <h2 class="">Edit Product</h2>
  <%=form_for(@inventory, :html=> {:class=> "add_prod_form"}) do |f|%>
    <div>
      <%=f.label :name, class: "prod_label"%>
      <%=f.text_field :name, class:"prod_input", 'title'=>'Product Name'%>
    </div>
    <div>
      <%=f.label "Units", class: "prod_label"%>
      <%= f.select :selling_units, ['KGS', 'BOX', 'PKT', 'NOS', 'BOT'],{ include_blank: false }, { :class => 'purchase_input purchase_select select_purchase_unit' }%>
      <%#=f.text_field :selling_units, class:"prod_input"%>
    </div>
    <div class="fields">
      <%= f.label :Select_Raw_Materials, class: "prod_label" %>
      <%= f.fields_for :items do |builder|%>
        <%a = Item.find(builder.object.id).merge_tables.where(inventory: @inventory, item_id: builder.object.id).first.quantity%>
        <%= render 'item', b: builder, itm_q: a%>
        <%#= builder.text_field :merge_table_ids, label: false, value: a, class:"prod_input prod_inp_quant"%>
      <% end %>
    </div>
    <div class="prod_btn_div">
      <%= submit_tag "Update", class:"prod_save" %>
      <%= link_to_add_row('Add Item', f, :items, class: 'add_raw ') %>
    </div>
    <!-- <div>
            <%=f.label :Raw_material, class: "prod_label"%>
            <%= collection_select(:item, :item_ids, Item.all, :id, :title, {}, { :multiple => true, class: "prod_input prod_select"} )%>
        </div> -->
  <%end%>
</div>

app/views/inventories/index.html.erb
<div class="items_container">
  <div class="item_cards">
    <% @inventories.each do |inventory|%>
      <div class="item_card">
        <div class="item_card_body">
          <div class="card_action">
            <span class="item_action_icon icon_edit">
              <%= link_to '<i class="fas fa-edit icon_edit"></i>'.html_safe, edit_inventory_path(inventory)%>
            </span>
            <span class="item_action_icon icon_delete">
              <!-- <i class="fas fa-trash-alt"></i> -->
              <%= link_to '<i class="fas fa-trash-alt icon_delete"></i>'.html_safe, inventory, confirm: 'Are you sure?', method: :delete %>
            </span>
          </div>
          <div class="card_title">
            <H2><b><%=inventory.name%></b></H2>
          </div>
          <div class="card_description">
            <%inventory.items.each do |item|%>
              <p>
                <%=item.title%>
                <%quant = item.merge_tables.where(inventory: inventory, item: item).first.quantity%>
                <%= "(" if quant%>
                <%= quant  if quant%>
                <%= Conversion.find_by(name: item.title).conversion_units if Conversion.find_by(name: item.title)%>
                <%= ")" if quant%>
              </p>
            <%end%>
          </div>
        </div>
      </div>
    <% end%>
  </div>
  <div class="item_popup" id="itm_btn">
    <i class="fas fa-plus"></i>
    <div class="itm_pop">
      <ul>
        <li><%=link_to "Add Product", new_inventory_path, class: "items_path"%></li>
        <li><%=link_to "Raw Materials", items_path, class: "items_path"%></li>
        <li><%=link_to "Conversions", conversions_path, class: "items_path"%></li>
        <ul>
        </div>
      </div>
    </div>

app/views/inventories/new.html.erb
<div class="form_container">
    <h2 class="">Add Product</h2>
    <%=form_for(@inventory, :html=> {:class=> "add_prod_form"}) do |f|%>
            <div>
                <%=f.label :name, class: "prod_label"%>
                <%=f.text_field :name, class:"prod_input"%>
            </div>
            <div>
                <%=f.label "Units", class: "prod_label"%>
                <%= f.select :selling_units, ['KGS', 'BOX', 'PKT', 'NOS', 'BOT'],{ include_blank: false }, { :class => 'purchase_input purchase_select select_purchase_unit' }%>
                <%#=f.text_field :selling_units, class:"prod_input"%>
            </div>
    
            <div class="fields">
                <%= f.label :Select_Raw_Materials, class: "prod_label" %>
                <%= f.fields_for :items do |builder|%>
                    <%= render 'item', b: builder, itm_q: 0%>
                <% end %>
            </div>
            
            <div class="prod_btn_div">
                <%= submit_tag "Create", class:"prod_save" %>
                <%= link_to_add_row('Add Item', f, :items, class: 'add_raw ') %>
            </div>

            <!-- <div>
                <%#=f.label :Raw_material, class: "prod_label"%>
                <%#= collection_select(:item, :item_ids, Item.all, :id, :title, {}, { :multiple => true, class: "prod_input prod_select"} )%>
            </div> -->
    <%end%>
</div>




 